controller_manager:
  ros__parameters:
    update_rate: 100 #  Hz

    joint_trajectory_controller:
      type: joint_trajectory_controller/JointTrajectoryController

    joint_state_broadcaster:
      type: joint_state_broadcaster/JointStateBroadcaster

    gazebo_joint_controller:
      type: forward_command_controller/ForwardCommandController

gazebo_joint_controller:
  ros__parameters:
    joints:
      - FR_hip_joint
      - FR_uleg_joint
      - FR_lleg_joint
      - FL_hip_joint
      - FL_uleg_joint
      - FL_lleg_joint
      - BR_hip_joint
      - BR_uleg_joint
      - BR_lleg_joint
      - BL_hip_joint
      - BL_uleg_joint
      - BL_lleg_joint
    interface_name: position
    command_interfaces:
      - position 
    state_interfaces:
      - position
      - velocity
      - effort